- vivado_messages.tcl
- vivado_proc.tcl
check is .DCP is invalid (usually due to git-lfs isssue)
> Escore 162

- vivado_proc.tcl
> bug fix for vcs build

- vivado_build.tcl
- vivado_gui.tcl
- vivado_post_route_run.tcl
- vivado_project.tcl
- vivado_properties.tcl
adding vivado_post_route_run.tcl support for GUI mode
> ESCORE-301

- vivado_cpsw.tcl
- vivado_pyrogue.tcl
Including the defaults config folder into either the pyrogue.tar.gz or cpsw.tar.gz
> ESCORE-304

- vivado_cpsw.tcl
- vivado_pyrogue.tcl
Create a copy of the tar.gz file with ones padding for PROM loading support (prevent Vivado from unzipping from the load)
> ESLCOMMON-193

- system_vivado.mk
###Description
v1.6.1 release broken the automatic clean detection
> v1.6.2 release candidate

- vivado_proc.tcl
> Syncing master to pre-release

- system_vivado.mk
- vivado_proc.tcl
Bug fixes for the Vivado 2018.1 release
[ESCORE-343](https://jira.slac.stanford.edu/browse/ESCORE-343)
> v1.6.4 release candidate

- vivado_build.tcl
- vivado_sources.tcl
bug fix to get the build string and incremental compile
Vivado version checking before polling PR_FLOW property
> v1.6.6 release candidate

- vivado_hls_build.tcl
- vivado_hls_dcp.tcl
- vivado_hls_proc.tcl
- vivado_hls_version.tcl
- vivado_proc.tcl
1. Added .ltx copying and CreatePromMcs to CreateFpgaBit { } 
2. HLS build time improvement
>  v1.6.7 release candidate

- vivado_build.tcl
- vivado_messages.tcl
- vivado_proc.tcl
- vivado_vcs.tcl
- Added syntax checking to vivado_vcs.tcl 
- Added arg to DcpToVerilogSim 
- Now support N-2017.12 after Ryan's C code bug fix 
- Added VCS_VERSION check
>   v1.6.9 release candidate

- system_vivado.mk
- vivado_build.tcl
- Adding parallel synthesis support for building Block Diagram’s IP cores
> Adding parallel synthesis support for building Block Diagram’s IP cores 

- system_vivado.mk
- vivado_build.tcl
- vivado_sources.tcl
- Adding parallel synthesis support for building Block Diagram’s IP cores
> v1.6.11 release candidate

- README.md
- vivado_proc.tcl
adding edif support
need to find a better way to add more file extensions to loadSource TCL proc
> adding edif support

- vivado_build.tcl
- vivado_post_synth_run.tcl
- Check for unsafe clock interaction report detection after synthesis
- Check for unconstrained Clocks in the clock network report after synthesis
[ESCORE-378](https://jira.slac.stanford.edu/browse/ESCORE-378)
> Additional clock checking in SYNTH.TCL.POST script

- vivado_post_synth_run.tcl
- vivado_pre_opt_run.tcl
- vivado_properties.tcl
- moving the unsafe timing checking from post-syn to pre-opt 
[ESCORE-387](https://jira.slac.stanford.edu/browse/ESCORE-387)
> Moving the unsafe timing checking from post-syn to pre-opt 

- vivado_build.tcl
- vivado_cpsw.tcl
- vivado_messages.tcl
- vivado_post_synth_run.tcl
- vivado_proc.tcl
- vivado_pyrogue.tcl
- vivado_vcs.tcl
- Adding edif support 
- Adding the .ltx file to the pyrogue.tar.gz and cpsw.tar.gz dump
- Check for "unsafe" in clock interaction report before place and route
- Allow building only HLS project through csynth, skip design export 
- New HLS Makefile target naming: [csyn, csyn_nocosim, dcp, dcp_nocosim]
> v1.7.0 release candidate

- system_vivado.mk
- vivado_build.tcl
- vivado_hls_build.tcl
- vivado_hls_dcp.tcl
- vivado_post_route.tcl
- vivado_pre_opt_run.tcl
- vivado_proc.tcl
- vivado_properties.tcl
- Casing on TIG env var for unsafe timing checking 
- HLS bug fixes for Vivado 2018.3
- Updating to Vivado 2018.3 AUTO_INCREMENTAL_CHECKPOINT 
- Adding support for future synth_1 AUTO_INCREMENTAL_CHECKPOINT (assuming support starts in Vivado 2019.1)
> v1.7.3 release candidate

- vivado_vcs.tcl
This PR updates the surf simulation library directory search to look for an of the three simulation modules which will be defined in the upcoming surf release.
> Update simulation source directory

- vivado_proc.tcl
- vivado_properties.tcl
- Update simulation source directory (https://github.com/slaclab/ruckus/pull/95)
>  v1.7.4 release candidate

- vivado_proc.tcl
- vivado_promgen.tcl
- bug fix for older versions of Vivado
- adding print statements
> v1.7.7 release candidate

- system_vivado.mk
- vivado_build.tcl
- vivado_post_route_run.tcl
- vivado_proc.tcl
- vivado_promgen.tcl
- vivado_properties.tcl
- vivado_vcs.tcl
- options to include .gz and .bin (not included by default) 
- VCS datafile bug fix
> v1.7.9 release candidate

- system_vivado.mk
- vivado_messages.tcl
- vivado_proc.tcl
- vivado_project.tcl
- vivado_pyrogue.tcl
- vivado_vcs.tcl
- Vivado 2019.1 support
- https://jira.slac.stanford.edu/browse/ESCORE-435
- adding .mem filetype support to loadSource()
- adding .mem filetype support to vivado_vcs.tcl
- adding zip file to vivado_pyrogue.tcl
- export XILINX_LOCAL_USER_DATA = no
- https://www.xilinx.com/support/answers/63253.html
- Adding Verdi support to VCS script
> v1.8.0 release candidate

- vivado_build.tcl
- vivado_messages.tcl
- vivado_proc.tcl
- vivado_project.tcl
- vivado_properties.tcl
- vivado_sdk_elf.tcl
- vivado_sdk_prj.tcl
- adding vivado patch version checking support
> adding vivado patch version checking support

- vivado_proc.tcl
- adding ability to ignore specific parametric timing results
> adding ability to ignore specific parametric timing results

- vivado_build.tcl
- vivado_cpsw.tcl
- vivado_post_route.tcl
- vivado_proc.tcl
- vivado_pyrogue.tcl
- removing ruckus git auto-tagging and build.info generation
> removing ruckus git auto-tagging and build.info generation

- vivado_pyrogue.tcl
- Removing .pyrogue.tar.gz generation from vivado_pyrogue.tcl
> removing .pyrogue.tar.gz generation from vivado_pyrogue.tcl

- vivado_build.tcl
- vivado_cpsw.tcl
- vivado_post_route.tcl
- vivado_proc.tcl
- vivado_pyrogue.tcl
> Revert "removing ruckus git auto-tagging and build.info generation"

- vivado_vcs.tcl
- adding pre and post user SourceTclFile()
> adding pre and post user SourceTclFile()

- vivado_sdk_elf.tcl
- vivado_sdk_prj.tcl
- bug fix for vivado_sdk_elf/vivado_sdk_prj not supporting vivado_proc.tcl
> bug fix for vivado_sdk_elf/vivado_sdk_prj not supporting vivado_proc.tcl

- vivado_proc.tcl
- `CreateDcpVhoFiles` gets a list of all the .dcp files in a project then iterates through the list to generate a .vho file in the same location of the .dcp file
> adding CreateDcpVhoFiles

- system_vivado.mk
- Maximize parallel synthesis if PARALLEL_SYNTH not defined
> system_vivado.mk: PARALLEL_SYNTH update

- vivado_sources.tcl
> Revert "Put BuildInfoPkg.vhd in ruckus library"

- vivado_sources.tcl
- Resolve the VHDL library issue with auto-generated `BuildInfoPkg.vhd`
> v2.0.1 release candidate

- vivado_proc.tcl
- formatting `CreateDcpVhoFiles` to component declaration template
> formating CreateDcpVhoFiles to component declaration template

- system_vivado.mk
- vivado_batch.tcl
- vivado_gui.tcl
- vivado_vcs.tcl
- vivado_wis.tcl
- adding 'batch' Makefile target
- some code header clean up
> Batch mode

- system_vivado.mk
- vivado_batch.tcl
- vivado_proc.tcl
- vivado_vcs.tcl
- vivado_wis.tcl
- TCL support for loadBlockDesign & CopyBdCores #130
- Batch mode #131
> v2.0.3 release candidate

- system_vivado.mk
- vivado/post_route.tcl
- vivado/proc.tcl
- vivado/pyrogue.tcl
- restoring vivado/pyrogue.tcl as stop gap measure until releaseGen.py development is completed (including example + minimal documentation)
> restoring vivado/pyrogue.tcl

- system_vivado.mk
- vivado/proc.tcl
- updating naming convention to always use _ before a sub-type
>  sub-type filename update

- vivado/pyrogue.tcl
- no longer ${PyRogueDirName} directory after uncompression
> Updating the Rogue zip

- system_vivado.mk
bug fix when vitis not in $PATH
> bug fix when vitis not in $PATH

- .gitignore
- MicroblazeBasicCore/sdk/bit.tcl
- MicroblazeBasicCore/sdk/elf.tcl
- MicroblazeBasicCore/sdk/prj.tcl
- MicroblazeBasicCore/vitis/bit.tcl
- MicroblazeBasicCore/vitis/elf.tcl
- MicroblazeBasicCore/vitis/prj.tcl
- releaseGen.py
- releaseNotes.py
- system_vivado.mk
- vivado/messages.tcl
- vivado/post_route.tcl
- vivado/proc.tcl
- vivado/pyrogue.tcl
- bug fix for MicroblazeBasicCore/sdk & MicroblazeBasicCore/vitis #138
- Pyrogue Update #139
- sub-type filename update #140
- Updating the Rogue zip #141
- Update releaseGen & releaseNotes #142
- bug fix when vitis not in $PATH #145
- vivado/messages.tcl updates #146
- Add conda build files as well as LICENSE.txt to zipfile. #144
- MicroblazeBasicCore Development Updates #147
> v2.1.0 release candidate

- system_vivado.mk
https://jira.slac.stanford.edu/browse/ESLCOMMON-264
> releaseGen.py needs to be called with python3

- releaseGen.py
- system_vivado.mk
- vivado/proc.tcl
- only set VHDL lib property to VHDL files in loadSource() #149
- releaseGen.py needs to be called with python3 #150
- Clarify the path of the generated zipfile #151
> v2.1.1 release candidate

- releaseGen.py
- Replace username/password with git token #153
> v2.1.2 release candidate

- vivado/build.tcl
- adding user post-build script call
> adding user post-build script call

- vivado/messages.tcl
- setting multi-drive pin to ERROR
> setting multi-drive pin to ERROR

- vivado/proc.tcl
- vivado/project.tcl
- vivado/sources.tcl
- Resolves bug when you do "make bit" then "make gui" and the results of synth_1/impl_1 are lost when the GUI pops up
> resolve bug where syth_1/impl_1 design reset after batch build

- releaseGen.py
https://bugs.python.org/issue21751
> zipimport does not support compression

- system_vivado.mk
- Images should be attached to release tags and not committed directly now
> removing image commit message

- releaseGen.py
- system_vivado.mk
- vivado/build.tcl
- vivado/messages.tcl
- vivado/proc.tcl
- vivado/project.tcl
- vivado/sources.tcl
- Release Gen Updates #156
- adding user post-build script call #155
- setting multi-drive pin to ERROR #157
- resolve bug where syth_1/impl_1 design reset after batch build #158
- Add support for script install and conda dependencies #159
- Release Script Updates #160
- zipimport does not support compression #161
- removing image commit message #163
- Support primary releases #164
> v2.2.0 release candidate

- system_vivado.mk
- vivado/project.tcl
- vivado/sources.tcl
- moving the vivado/project.tcl into vivado/sources.tcl
> moving the vivado/project.tcl into vivado/sources.tcl

- releaseNotes.py
This PR will add pull request labels to the release notes headers. The labels will allow the release notes to indicate if the PR was a new feature or bug request.
> Add Pull Request Labels Release Notes

- releaseGen.py
- releaseNotes.py
- Allow user to store github token in their environment #171
- Add Pull Request Labels Release Notes #172
> v2.3.0 release candidate

- .flake8
- .gitattributes
- .gitignore
- .travis.yml
- scripts/createNewRepo.py
- scripts/firmwareRelease.py
- scripts/releaseNotes.py
- scripts/write_vhd_synth_stub_parser.py
- vivado/dcp.tcl
- Added script to make new Github repos
- Misc. flake8 (Python Linter) cleanup
> adding  scripts/createNewRepo.py

- .flake8
- .gitattributes
- .gitignore
- .travis.yml
- scripts/createNewRepo.py
- scripts/firmwareRelease.py
- scripts/releaseGen.py
- scripts/releaseNotes.py
- scripts/write_vhd_synth_stub_parser.py
- system_vivado.mk
- vivado/dcp.tcl
- vivado/messages.tcl
- vivado/proc.tcl
- Adding findFiles proc #178
- Adding loadZipIpCore() #179
- adding scripts/createNewRepo.py #180
- prevent adding duplicate loadZipIpCore #181
- Add release type to release name #182
> Release Candidate v2.5.0

- scripts/firmwareRelease.py
- scripts/releaseNotes.py
- Add missing f-strings in firmwareRelease.py #184
> release candidate v2.5.1

- MicroblazeBasicCore/vitis/prj.tcl
- vivado/proc.tcl
> Vivado 2020.1 Support

- scripts/firmwareRelease.py
- Add support for cpp libraries in firmware release #196
> release candidate v2.7.0

- scripts/firmwareRelease.py
This appears to work on ubuntu machines and on travis.
> Fix anaconda builds

- scripts/firmwareRelease.py
- vivado/proc.tcl
- bug fix for version checking and write_hw_platform #198
- Fix anaconda builds #199
> release candidate v2.7.1

- .flake8
- scripts/releaseGen.py
- Check if release tag already exists before executing the release tag procedure
> release candidate v2.7.2

- scripts/firmwareRelease.py
- vivado/messages.tcl
- Update firmwareRelease.py #202
- elevating timing not meet messages to ERROR message #203
> Release Candidate v2.7.4

- vivado/messages.tcl
- bug fix for TIG support #205
> Release Candidate v2.7.5

- system_vivado_hls.mk
- vivado/hls/build.tcl
- vivado/proc.tcl
- adding Vivado 2020.2 support #207
> Release Candidate v2.8.0

- vivado/gui.tcl
- vivado/messages.tcl
- vivado/proc.tcl
- vivado/properties.tcl
- vivado/messages.tcl update #211
- adding versal support #212
> Release Candidate v2.9.0

- .github/workflows/ruckus_ci.yml
- LICENSE.txt
- updating LICENSE.txt
- Update ruckus_ci.yml
> Release Candidate v2.9.1

- .github/workflows/ruckus_ci.yml
- update build string from x86_64 to distro/kernel version #215
> Release Candidate v2.9.2

- vivado/batch.tcl
- vivado/gui.tcl
- vivado/post_synth_run.tcl
- vivado/properties.tcl
- vivado/run/post/gui_write.tcl
- vivado/run/post/opt.tcl
- vivado/run/post/phys_opt.tcl
- vivado/run/post/place.tcl
- vivado/run/post/post_place_power_opt.tcl
- vivado/run/post/post_route_phys_opt.tcl
- vivado/run/post/power_opt.tcl
- vivado/run/post/route.tcl
- vivado/run/post/synth.tcl
- vivado/run/pre/opt.tcl
- vivado/run/pre/phys_opt.tcl
- vivado/run/pre/place.tcl
- vivado/run/pre/post_place_power_opt.tcl
- vivado/run/pre/post_route_phys_opt.tcl
- vivado/run/pre/power_opt.tcl
- vivado/run/pre/route.tcl
- vivado/run/pre/synth.tcl
- reorg of existing pre/post run scripts
- adding report_qor_assessment/report_qor_suggestions to synth_1
- adding report_qor_assessment/report_qor_suggestions to impl_1
> Adding `report_qor_assessment` and `report_qor_suggestions` Reporting

- Doxyfile
- README.md
- scripts/createNewRepo.py
- vivado/proc.tcl
- vivado/properties.tcl
- vivado/run/post/gui_write.tcl
- vivado/run/post/opt.tcl
- vivado/run/post/phys_opt.tcl
- vivado/run/post/place.tcl
- vivado/run/post/post_place_power_opt.tcl
- vivado/run/post/post_route_phys_opt.tcl
- vivado/run/post/power_opt.tcl
- vivado/run/post/route.tcl
- vivado/run/post/synth.tcl
- vivado/run/pre/opt.tcl
- vivado/run/pre/phys_opt.tcl
- vivado/run/pre/place.tcl
- vivado/run/pre/post_place_power_opt.tcl
- vivado/run/pre/post_route_phys_opt.tcl
- vivado/run/pre/power_opt.tcl
- vivado/run/pre/route.tcl
- vivado/run/pre/synth.tcl
-  Added BYPASS_VERSION_CHECK to VersionCheck #217 
- Adding `report_qor_assessment` and `report_qor_suggestions` Reporting #218
- Github now uses main (instead of master) for default branch #220
> Release Candidate v2.10.0

- .gitattributes
- .gitignore
- MicroblazeBasicCore/sdk/bit.tcl
- MicroblazeBasicCore/vitis/bit.tcl
- vivado/batch.tcl
- vivado/build.tcl
- vivado/gui.tcl
- vivado/proc.tcl
- vivado/properties.tcl
- vivado/run/post/gui_write.tcl
- bug fix for `GenerateBdWrappers` proc
- Casing on `[isVersal]` to use `STEPS.WRITE_DEVICE_IMAGE` over `STEPS.WRITE_BITSTREAM`
- adding `CreateVersalOutputs` and `CopyLtxFile` procs
> Versal Development Updates

- vivado/proc.tcl
- vivado/vcs.tcl
- adding R-2020.12 to VCS support list #223
> Release Candidate v3.0.1

- system_mps430.mk
- system_shared.mk
- system_vcs.mk
- Adding `system_mps430.mk`
- Some whitespace removal
> Addding support to compile MPS430

- .gitattributes
- .gitignore
- system_mps430.mk
- system_shared.mk
- system_vcs.mk
- vivado/post_route.tcl
- vivado/proc.tcl
- Adding support to compile MPS430 #229
- adding support for Vivado 2021.1 #231
> Release Candidate v3.1.0

- system_vivado.mk
- vivado/run/post/opt.tcl
- vivado/run/post/place.tcl
- vivado/run/post/route.tcl
- vivado/run/post/synth.tcl
- enables the support to bypass QOR reports to speed up build times
> adding REPORT_QOR

- .gitattributes
- .gitignore
- system_vivado.mk
- vivado/run/post/opt.tcl
- vivado/run/post/place.tcl
- vivado/run/post/route.tcl
- vivado/run/post/synth.tcl
> Release Candidate v3.1.1

- vitis/hls/build.tcl
- vitis/hls/proc.tcl
- vivado/run/pre/synth.tcl
> Release Candidate v4.1.0

- vitis/hls/build.tcl
- vitis/hls/proc.tcl
- vitis/hls/sources.tcl
- removing loadSourcesTcl() because global variables not support in HLS TCL
- resolve namespace conflict when using c++ templates in HLS
> Release Candidate v4.1.1

- system_vitis_hls.mk
- vivado/proc.tcl
- Fixed some typos
- Placeholders for HLS SKIP_DCP
- updating to message for 2021.2 support
> Release Candidate v4.1.2

- vivado/proc.tcl
- Turns out the set_property is_enabled false was actually making the 'make bit' and 'make gui' not the same results.
> BuildIpCores() update

- vivado/proc.tcl
> Release Candidate v4.1.3

- LICENSE.txt
- vivado/messages.tcl
- vivado/vcs.tcl
> Release Candidate v4.1.4

- scripts/releaseNotes.py
> Release Candidate v4.1.5

- vivado/post_route.tcl
> Release Candidate v4.1.7

- synopsys/design_compiler/env_var.tcl
- synopsys/design_compiler/proc.tcl
- synopsys/design_compiler/sim.sh
- synopsys/design_compiler/syn.tcl
- system_synopsys_dc.mk
- system_vivado.mk
> Release Candidate v4.2.0

- synopsys/design_compiler/syn.tcl
- [bug fix for synopsys/design_compiler/syn.tcl](https://github.com/slaclab/ruckus/commit/2afb22974c140f16ddc6560f69c5ae62e26e0e7f)
> Release Candidate v4.2.1

- scripts/createNewRepo.py
- [updating team names that have recently changed](https://github.com/slaclab/ruckus/commit/a17b9bbe9dea2f1152b402eb58932e795291c24c)
> createNewRepo.py update

- scripts/bin2txt.py
-  Script to convert the .bin file from [opalkelly](https://opalkelly.com/tools/fmceepromgenerator/)  into a .txt file for [DM160237 I2C Evaluation Kit GUI](https://www.microchip.com/en-us/development-tool/DM160237)
> adding scripts/bin2txt.py

- scripts/bin2txt.py
- scripts/createNewRepo.py
> Release Candidate v4.3.2

- synopsys/design_compiler/syn.tcl
- [copying .sdc for synopsys/design_compiler](https://github.com/slaclab/ruckus/commit/25acb92f5770039faf2c6872de06a94862c5476b)
> Release Candidate v4.3.3

- .gitattributes
- .gitignore
- system_vitis_hls.mk
- system_vivado.mk
- vivado/messages.tcl
- vivado/proc/code_loading.tcl
- vivado/proc/project_management.tcl
- [adding support for ALLOW_PARTIAL_SENSE_LIST](https://github.com/slaclab/ruckus/commit/f95a514aa4198ae7fc05310b00e5eea7293ced6e)
- [Updated .gitignore](https://github.com/slaclab/ruckus/commit/b4153fa0a9009525d62d303afbf0d17e04880f92)
- [adding .svh support to loadSource()](https://github.com/slaclab/ruckus/commit/cef57f0cc409bfd59c33b6bb6964fa04eaa3a195)
- [Adding .h5 to git-lfs](https://github.com/slaclab/ruckus/commit/a2058da005d75300c8b0e5afd33baeb34ac28881)
- bug fixes for Vivado 2022.1
> Release Candidate v4.3.4

- scripts/firmwareRelease.py
- vivado/messages.tcl
- [allow GTGREFCLK & GTHE3_COMMON](https://github.com/slaclab/ruckus/commit/32649f0b4be5f36abe66a9140a49517a34af120e)
- [scripts/firmwareRelease.py update](https://github.com/slaclab/ruckus/commit/a2378b2a2a921208868df3ff4ff03e0d6864ac29)
> Release Candidate v4.3.5

- .gitignore
- scripts/firmwareRelease.py
- firmwareRelease.py bug fix
- [Update .gitignore](https://github.com/slaclab/ruckus/commit/0f4ca2f7534d2b8127af1c2bad7e075cef5fefd4)
> Release Candidate v4.3.6

- scripts/firmwareRelease.py
- system_vivado.mk
- vivado/proc/debug_probes.tcl
- vivado/proc/project_management.tcl
- vivado/vcs.tcl
- [verified vivado 2022.2](https://github.com/slaclab/ruckus/commit/cfa0be102c280aacdbdbce47606f4e3bdd825873)
- [verified VCS T-2022.06 support](https://github.com/slaclab/ruckus/commit/e405776aaa8df8d500235aff9d90e8cd511caed7)
- #266 
- [resolved 'E275 missing whitespace after keyword' flake8 errors](https://github.com/slaclab/ruckus/commit/3f406dabd07e3c7d474266e61ab645711eaef2ed)
> Release Candidate v4.4.0

- .flake8
- https://www.reddit.com/r/Python/comments/z6itb8/new_flake8_60_has_a_bug_which_breaks_repos/
- [Updating to insert comments into the .flake8 in the recommend way in the documentation](https://flake8.pycqa.org/en/latest/user/configuration.html)
> reorg the .flake8 structure to address error in flake8 v6.0.0

- fabulous/build.tcl
- fabulous/env_var.tcl
- fabulous/proc.tcl
- system_fabulous.mk
- Based on `FABulous refactor` version
- https://github.com/FPGA-Research-Manchester/FABulous/pull/50
- Currently only support a signle top-level HDL eFPGA bitstream file build
- Plan to add support for multiple files via ruckus.tcl loading in the future
> Adding `FPGA-Research-Manchester/FABulous` support

- .flake8
- cadence/genus/env_var.tcl
- cadence/genus/proc.tcl
- cadence/genus/sim.sh
- cadence/genus/syn.tcl
- fabulous/build.tcl
- fabulous/env_var.tcl
- fabulous/proc.tcl
- system_cadence_genus.mk
- system_fabulous.mk
- vivado/proc/sim_management.tcl
- vivado/vcs.tcl
- #268 
- #269
- #270 
- #271 
- #272
> Release Candidate v4.5.0

- system_vivado.mk
- vivado/msim.tcl
- vivado/xsim.tcl
> Release Candidate v4.6.0

- .gitignore
- system_shared.mk
- system_vivado.mk
- Added `*.swp` to .gitignore
- Change GIT_HASH_MSG from `dirty` to `dirty (uncommitted code)`
- #278
> Release Candidate v4.6.1

- scripts/releaseNotes.py
Add `Documentation` tag sorting when auto generating release notes.
> Add  to list of sorted tags

- fabulous/proc.tcl
- synopsys/design_compiler/env_var.tcl
- synopsys/design_compiler/syn.tcl
- system_fabulous.mk
- [adding Fabulous Interactive mode](https://github.com/slaclab/ruckus/commit/a9a16c523a1edd22d693d119e9635b65f975099c)
- [moving local variables to env_var.tcl](https://github.com/slaclab/ruckus/commit/759fab2c4ef2b93aa269e51c94d0eea63dfbd67c)
- [adding post_fabric.tcl ability to fabulous work flow](https://github.com/slaclab/ruckus/commit/6f47a7cb82de7696ad4dce12170024b218612546)
> fabulous Updates

- cadence/genus/syn.tcl
- adding the missing _g.v copy to image dir
> Cadence Genus Bug Fix

- cadence/genus/messages.tcl
- cadence/genus/proc.tcl
- cadence/genus/syn.tcl
- fabulous/proc.tcl
- synopsys/design_compiler/env_var.tcl
- synopsys/design_compiler/syn.tcl
- system_cadence_genus.mk
- system_fabulous.mk
> Release Candidate v4.7.0

- system_shared.mk
- system_vivado.mk
> Release Candidate v4.7.1

- .gitignore
- scripts/firmwareRelease.py
- [Adding images* to .gitignore](https://github.com/slaclab/ruckus/commit/3625b995d8726590228c0e52528d6c9a614024f1)
- [Conda Fix](https://github.com/slaclab/ruckus/commit/a04be68fcec0d678452fc7a62fe4ed2a675a9de8)
> Release Candidate v4.7.2

- .gitignore
- scripts/firmwareRelease.py
- [Update .gitignore](https://github.com/slaclab/ruckus/commit/59588a072ec2d4a4f0a5b28c66bba66fd7664c6a)
- #293
> Release Candidate v4.7.3

- ghdl/import.tcl
- system_cadence_genus.mk
- system_fabulous.mk
- system_synopsys_dc.mk
- system_vivado.mk
- vivado/proc/sim_management.tcl
- [Updating VcsCompleteMessage Verdi GUI command](https://github.com/slaclab/ruckus/commit/da96bf53f1e38d361ea9cb601ae66b6d10c10a60)
- [removing RUCKUS_PROC_TCL env var](https://github.com/slaclab/ruckus/commit/c813b3d344242da42df795c09ebb3e553ae9ba67)
> Release Candidate v4.8.2

- .gitattributes
- .gitignore
- vivado/proc/project_management.tcl
- vivado/proc/sim_management.tcl
- [Adding .jou* to .gitignore](https://github.com/slaclab/ruckus/commit/620527277594d69022c80881fb53decb5c6afe9d)
- [Update .gitattributes](https://github.com/slaclab/ruckus/commit/075964e6f2863c71539489e63912275440a2b7f2)
- [updating supported Vivado release msg](https://github.com/slaclab/ruckus/commit/de1c8601814f00e2574dd1a8d7e310bf8a9a4e70)
> Release Candidate v4.8.3

- system_vcs.mk
- system_vivado.mk
- vivado/proc/sim_management.tcl
- vivado/sources.tcl
- vivado/vcs.tcl
> Release Candidate v4.8.5

- vivado/messages.tcl
- vivado/proc/code_loading.tcl
- This will help us catch .XCI that get broken after doing a XML-to-JSON upgrade
> changing 'IP_FLOW: Failed to register IP shared directory path' from warning to error

- system_vivado.mk
- vivado/proc/output_files.tcl
- vivado/promgen.tcl
- Feature request from @bengineerd to reduce number of files in target dir that will never be used
> Vivado: adding ability to bypass bit and/or xsa copy

- system_vivado.mk
- vivado/proc/code_loading.tcl
- vivado/proc/output_files.tcl
- vivado/promgen.tcl
- vivado/xsim.tcl
> Release Candidate 4.10.0

- LICENSE.txt
> Release Candidate 4.10.1

- .github/workflows/conda_build_lib.yml
- .github/workflows/gen_release.yml
- scripts/download_github_asset.py
- shared/proc.tcl
- [bug fix in latest $::env(BUILD_STRING) to trim quotes off at the end](https://github.com/slaclab/ruckus/commit/d9d27b430b027a586ebacbd497ce8fa5939d8694)
- adding download_github_asset.py script
- #314
> Release Candidate 4.12.0

- .github/workflows/gen_release.yml
- Update gen_release.yml: newer versions and fixes the deprecetated set-output
> Release Candidate 4.12.1

- vitis/hls/build.tcl
- vitis/hls/proc.tcl
- reverting back to ruckus v3 style of HLS filename to clean up the number of copies in the ip dir
> update to HLS file name

- scripts/createNewRepo.py
- This is in an effort to migrate away from ssh-key in cloning project
> updating scripts/createNewRepo.py to use HTTPS (instead of ssh-key)

- vivado/proc/project_management.tcl
- Pass all my regression test projects builds
- No additional changes required
> Completed regression testing of Vivado 2024.1

- .gitattributes
- vivado/proc/project_management.tcl
- [Update .gitattributes: Adding .hdf5 to git-lfs](https://github.com/slaclab/ruckus/commit/5c77da4e1be2c24348aa1e139e9a0ae5f43d7e88)
- #321
> Release Candidate 4.13.1

- vivado/msim.tcl
- vivado/proc/sim_management.tcl
- #323
- Adding conda_build_proj.yml re-useable Github action CI script
> Release Candidate 4.14.0

- .gitattributes
- Assigning `.doc` and `.docx` to git-lfs
- ruckus/.gitattributes is used as a template for creating new repos
- For `.github/workflows/conda_build_lib.yml`
- Splitting the Build And Upload into two steps
- Change the hard coded `noarch` to '*' for anaconda upload to make this script for general
> Release Candidate 4.14.1

- system_vitis_unified_hls.mk
- vitis/hls/build.py
- vitis/hls/create_proj.py
> Release Candidate 4.16.0

- vivado/proc/ip_management.tcl
- [bug fix for locked IPs due to "retarget IP"](https://github.com/slaclab/ruckus/commit/ecebd549eb2bed087b9438b1f5b763c2497b6aea)
> Release Candidate 4.16.1

- vivado/gui.tcl
- vivado/proc/code_loading.tcl
- vivado/proc/ip_management.tcl
- [adding support to check if old user IP is different to new user IP](https://github.com/slaclab/ruckus/commit/47bc886dda208a5378ce1e6fac737991088da584)
> Updates to the loadZipIpCore TCL proc

- vivado/gui.tcl
- vivado/proc/code_loading.tcl
- vivado/proc/debug_probes.tcl
- vivado/proc/ip_management.tcl
- vivado/vcs.tcl
- adding vcs W-2024.09 support
- #333
> Release Candidate 4.17.0

- .github/workflows/conda_build_lib.yml
- .github/workflows/conda_build_proj.yml
- .github/workflows/conda_build_win.yml
- .github/workflows/docker_build_lib.yml
- .github/workflows/gen_release.yml
- .github/workflows/ruckus_ci.yml
- vivado/build.tcl
- #336
- [migrating CI from ubuntu-20.04 to ubuntu-24.04](https://github.com/slaclab/ruckus/pull/337/commits/3ac8320232ce11e338c19404766e5f0065b05d8c)
> Release Candidate 4.17.4

- README.md
- vivado/gui.tcl
- vivado/messages.tcl
- vivado/proc/ip_management.tcl
- [Changing filemgmt 56-315 from warning to error message](https://github.com/slaclab/ruckus/commit/a92b877d511ea690a9cb2e9a804ad595a36a3259)
- [filemgmt 56-315] Source scanning failed during design analysis. To get more details run synthesis or simulation and check the log.
- [Check if the target project has IP cores before attempt to upgrade before building IP cores](https://github.com/slaclab/ruckus/pull/338/commits/f5f84f27aca6ff494e10007991db52609ae8647d)
- [Update README.md to include DOE code reference](https://github.com/slaclab/ruckus/pull/338/commits/23712688fc310b9e0aaee534f4b321aa6ab1e82c)
> Release Candidate 4.17.5

- system_cadence_genus.mk
- system_fabulous.mk
- system_shared.mk
- system_synopsys_dc.mk
- system_vitis_hls.mk
- system_vitis_unified_hls.mk
- system_vivado.mk
- bug that was introduced in make version 4.4.1
- https://savannah.gnu.org/bugs/?64746
> work around for GNU Make bug #64746

- system_cadence_genus.mk
- system_fabulous.mk
- system_shared.mk
- system_synopsys_dc.mk
- system_vitis_hls.mk
- system_vitis_unified_hls.mk
- system_vivado.mk
- vivado/proc.tcl
- #339
- #341
- [work around for '[Common 17-356] Failed to install all user apps' error message](https://github.com/slaclab/ruckus/pull/340/commits/f124fca0687c3f537b3308b9d77948d5a266b294)
> Release Candidate 4.17.6

- .github/workflows/docker_build.yml
- shared/proc.tcl
- system_vitis_hls.mk
- [updating BuildInfoPkg.vhd generation to match slaclab/surf/vsg-linter.yml](https://github.com/slaclab/ruckus/commit/209f3b770b1c4009327f1c26569fb2a30e13c813)
- #342 
- #344
> Release Candidate 4.17.7

- .github/workflows/conda_build_lib.yml
- .github/workflows/conda_build_proj.yml
Attempt to fix anaconda error by removing conda-verify package
> Attempt to fix anaconda error by removing conda-verify package

- vivado/pre_synthesis.tcl
- vivado/proc/ip_management.tcl
- [GenerateBdWrappers update: Attempt to create the wrapper and catch an error](https://github.com/slaclab/ruckus/commit/63b6048bc2ee81cc3a210af3f164c23dadc8c525)
- [skip GenerateBdWrappers in pre_synthesis.tcl if Versal](https://github.com/slaclab/ruckus/commit/e3db0b3ed58bd09f22cd45c4c3ff05e78878f9e9)
> Release Candidate 4.17.9

- scripts/firmwareRelease.py
- vivado/proc/project_management.tcl
- vivado/proc/sim_management.tcl
- [Update sim_management.tcl](https://github.com/slaclab/ruckus/commit/a4d5e1b3f9933c659c1b7943f111890a7bdfb9de)
- [adding VersionRangeCheck() proc](https://github.com/slaclab/ruckus/commit/47c0620ec404b58f0704fd374bc6d83eb768ef39)
- [raise exception if target image dir is empty or targets not found](https://github.com/slaclab/ruckus/pull/358/commits/86fc34eb33ae86553ab1c9e3a2b6430c08a5deef)
> Release Candidate 4.20.0
