- vivado_messages.tcl
This may break some builds. Maybe we allow undriven by default? Comments?
> generate an error for undriven nets

- system_vivado.mk
The proposed addition saves the debugProbes.ltx file (if such a file was created during implementation) in the 'images' area along with the bit file and with the same name prefix as the bit file.
This ensures that probes matching a particular bitstream are preserved along with it.
> Save debug probes

- system_vivado.mk
- vivado_proc.tcl
- vivado_wis.tcl
In CheckGitVersion, reducing version check to v2.9.0
removing export GIT_DIFF in system_vivado.mk
[ESROGUE-229](https://jira.slac.stanford.edu/browse/ESROGUE-229)
[ESROGUE-230](https://jira.slac.stanford.edu/browse/ESROGUE-230)
> v1.6.5 release candidate

- vivado_proc.tcl
Xilinx deprecated the IS_AUTO_DISABLED property, so the method we were using no longer works.
The comments note that this way causes DRC errors. I'm running a test build now to see if I find any.
> Switch to a different RemoveUnusedCode routine

- vivado_proc.tcl
- vivado_sources.tcl
- vivado_vcs.tcl
- added Verilog include/define support
- added VCS version checking
- fixed bug with VHDL only simulations
- added zeromq checking for rogue sim
- added auto-detection of RogueSim.vhd (symbol link no longer required)
> vivado_vcs.tcl update

- system_vivado.mk
- system_vivado_hls.mk
- vivado_hls_build.tcl
3 proposed changes in this pull request:
**1)  Allow building only HLS project through csynth, skipping design export.**
Introduced two additional make targets, hls and hls_fast. One can play with the
HLS algo first and inspect csynth report first before proceeding with full design export.
**2)  Copy HLS csynth report to ip/ directory**
**3) Set HLS Simulation Tool in top Makefile. (the change is backward compatible, with vcs set as default ).**
One can override VCS as the default HLS simulation tool and specify any simulator supported by Vivado HLS. This can be achieved by exporting HLS_SIM_TOOL variable in user's Makefile.
e.g. Vivado Simualtor
export HLS_SIM_TOOL = xsim
> Additional features for HLS projects

- system_vivado.mk
- bug fix for githash in the build image name with extra zero when doing non-partial reconfiguration FW
> v1.7.8 release candidate

- system_vivado.mk
- Avoid placing an extra '0' on the end of the githash in the filename
> Avoid placing an extra '0' on the end of the githash in the filename

- system_vivado.mk
- vivado_build.tcl
- vivado_gui.tcl
- vivado_messages.tcl
- vivado_proc.tcl
- vivado_project.tcl
- vivado_properties.tcl
- vivado_sdk_elf.tcl
- vivado_sdk_prj.tcl
- vivado_vcs.tcl
- adding vivado patch version checking support #106
- Avoid placing an extra '0' on the end of the githash in the filename #107
- adding support for user gui startup script
- Added vlogan option: +define+SIM_SPEED_UP
- This is commonly used in Xilinx IP cores to speed up the simulation. 
Example: Refer to Integrated 100G Ethernet v2.6 (PG203) on page 216
> v1.8.1 release candidate

- vivado_project.tcl
- Inspired by https://gitlab.cern.ch/asvetek/apxfs-ref-prj/blob/8430cce0/apd1/vivado/properties.tcl
- general.maxThreads doesn't appear to have upper limit
- synth.maxThreads can't be greater than 8
```
set_param synth.maxThreads ${cpuNum}
ERROR: [Common 17-154] Value should be >= 1 and <= 8
```
> Maximizing max thread by default

- vivado_sources.tcl
This puts `BuildInfoPkg.vhd` into a library called `ruckus`. 
This is related to our push to vhdl libraries.
https://github.com/slaclab/surf/pull/541
> Put BuildInfoPkg.vhd in ruckus library

- vivado_project.tcl
- Up to Vivado 2018.2, general.maxThreads was limited to 8 and from 2018.3 onwards the limit increased to 32.
- Default and max thread count values can be collected with "report_param" TCL command
> Fix version dependent Vivado multi-threading count for general.maxThreads

- vivado_proc.tcl
- adding .TCL file support to loadBlockDesign()
- Example: `loadBlockDesign -path "$::DIR_PATH/bd/2018.3/MicroblazeBasicCore.tcl"`
- adding createTcl support to CopyBdCores
- combining CopyBdCores and CopyBdCoresDebug together
- combining CopyIpCores and CopyIpCoresDebug together
- .bd is a bit annoying - it contains the graphical placement info, etc. that's not so useful.  
- Hard to edit in a text editor
- TCL is easy to modify. (Example: change data bus 32->128bits) without opening Vivado GUI
[ESCORE-500](https://jira.slac.stanford.edu/browse/ESCORE-500)
> TCL support for loadBlockDesign & CopyBdCores

- vivado/post_route.tcl
- For auto-build generation, instead of checking if `${PROJ_DIR}/python` exists use if `::env(GEN_PYROGUE_ZIP)` exist
- Requires defining GEN_PYROGUE_ZIP in Makefile
> Pyrogue Update

- MicroblazeBasicCore/sdk/prj.tcl
- MicroblazeBasicCore/vitis/prj.tcl
- system_vivado.mk
- vivado/messages.tcl
- vivado/proc.tcl
- EMBED_PROC helps with the situation when both MicroblazeBasicCore.vhd and a Ultrascale MIG core is used and vivado rename the MicroblazeBasicCore.vhd's `proc` from `microblaze_0` to `U_CORE_U_CPU_U_Microblaze_microblaze_0`
- Elimate the requirement for a custom user script build and simply defined EMBED_PROC in Makefile instead
> MicroblazeBasicCore Development Updates

- vivado/proc.tcl
- This will remove these types of warnings ...
```
WARNING: [filemgmt 56-99] Vivado Synthesis ignores library specification for Verilog or SystemVerilog files.
```
> only set VHDL lib property to VHDL files in loadSource()

- releaseGen.py
This replaces the username/password prompt with a prompt for your git token in the releaseGen.py script.
> Replace username/password with git token

- releaseGen.py
- system_vivado.mk
- [adding BZIP2 compression to the release ZIP file](https://docs.python.org/3/library/bz2.html#bz2.BZ2File)
- releaseGen.py depends on the ~/firmware/build/VivadoProject dir
- v1.0.0 is with original code (no compression)
- v2.0.0 is with BZIP2 compression
```bash
$ ls -lath /u1/ruckman/build/SmurfKcu1500RssiOffload10GbE/rogue*
-rw-r--r-- 1 ruckman re 103M Feb 11 09:33 /u1/ruckman/build/SmurfKcu1500RssiOffload10GbE/rogue_SmurfKcu1500RssiOffload10GbE_v1.0.0.zip
-rw-r--r-- 1 ruckman re  31M Feb 11 09:33 /u1/ruckman/build/SmurfKcu1500RssiOffload10GbE/rogue_SmurfKcu1500RssiOffload10GbE_v2.0.0.zip
```
> Release Gen Updates

- releaseGen.py
This PR updates the releaseGen script with the following changes:
1. Allow scripts to be installed 
2. Allow user to define conda dependencies
3. Suggest user can enter no value for compare version
This includes some changes in the script structure to cleanup the code.
> Add support for script install and conda dependencies

- releaseGen.py
- system_vivado.mk
- adding RELEASE_DIR variable
- make PROJECT variable agnostic to string structure
- Example: Supports `export PROJECT=ClinkFebPgp3_1ch` target name
- adding support for repo level release
> Release Script Updates

- releaseGen.py
This allows the release to have a Primary flag which will not pre-pend the release tag with the release name. This is useful for single release repositories.
Releases:
axi_pcie_devel:
Primary: True
Targets:
- InterCardTest
- RateTestKcu1500
Types:
- Rogue
This PR also adds an error check to ensure the release name does not contain dashes.
> Support primary releases

- releaseGen.py
- system_vivado.mk
- enabling GZIP build images by default
- check if .gz image file exists 
- If exists, then use it instead for the rogue_XXX.zip
- force the extension to be exact
- Previously only declaring `.mcs` would grab both `.mcs` and the `.mcs.gz`
- $ indicates "end of the string"
- prevent file duplication writes in the zipFile
- Example: declaring both `.mcs` and `mcs.gz` in the releases.yaml
> releaseGen.py Updates

- releaseGen.py
- releaseNotes.py
In releaseGen.py, the tag message is now like this:
```
Major Release vX.0.0
Minor Release vX.Y.0
Patch Release vX.Y.Z
```
The releaseNotes.py script has also been tweaked to omit any "Release Candidate" PRs from the generated release notes, as these are unnecessary to include.
> Release script tweaks

- vivado/messages.tcl
- vivado/proc.tcl
- Bug fix for duplicated IP cores loaded when you load your design more than one time after a make clean
- Changed `[IP_Flow 19-1663] Duplicate IP found` from `warning` to `error`
> prevent adding duplicate loadZipIpCore

- scripts/firmwareRelease.py
- scripts/releaseNotes.py
Two strings in `firmwareRelease.py` should have been f-strings for string substitution. This is now fixed.
> Add missing f-strings in firmwareRelease.py

- scripts/releaseGen.py
Some repos don't use the vx.x.x format.
> Make leading v optional in version number

- MicroblazeBasicCore/vitis/prj.tcl
- scripts/releaseGen.py
- vivado/proc.tcl
- Vivado 2020.1 Support #186
- Make leading v optional in version number #187
> release candidate v2.5.2

- scripts/firmwareRelease.py
See 
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
for more information. We will use the unsafe loader.
> Avoid yaml loader deprecation error

- .gitignore
- vivado/vcs.tcl
- Updated `.gitignore` template
- Ignoring Vivado 2020 .xsa files
- Fixed the bug where VCS won't compile if you have a purely VHDL simulation #194
> release candidate v2.6.2

- scripts/firmwareRelease.py
This allows the user to include supporting cpp libraries in the firmware release. 
The user will add the following key/value under the target Release:
LibDir: ../path/to/lib/directory
That directory is expected to contain a CMakeLists.txt file which is used to build the library file. 
Here is an example library implementation:
https://github.com/slaclab/ucsc-hn/tree/master/software/lib
And the associated releases.yaml file:
https://github.com/slaclab/ucsc-hn/blob/master/firmware/releases.yaml
> Add support for cpp libraries in firmware release

- vivado/gui.tcl
- vivado/proc.tcl
- vivado/properties.tcl
- Update for Versal support
- Versal production add in Vivado 2020.2
- IP core .DCP no longer dump in source_1/ip dir in Vivado 2020.2
> adding versal support

- system_shared.mk
Before: `BuildServer  = rdsrv314 (x86_64)`
After: `BuildServer  = rdsrv314 (Ubuntu 20.04.1 LTS)`
> update build string from x86_64 to distro/kernel version

- vivado/proc.tcl
- Vivado 2020.3 is a `versal device only` release
- Verified 2020.3 Versal support on my edgeML dev git project still works
> Vivado 2020.3 Support

- vivado/build.tcl
- vivado/messages.tcl
- vivado/proc.tcl
- Vivado 2020.3 Support #225
- move setting synthesis to out_of_context to a new proc() command #227
- vivado/messages.tcl: Commenting Out {Route 35-39} #228
> Release Candidate v3.0.2

- scripts/releaseNotes.py
For the PRs found when scanning the git log, if the source branch is `pre-release` and the destination branch is `main`, then the script now assumes it is the Release Candidate PR and does not include it in the release notes.
> Do not include Release Candidate PRs in generated release notes

- .gitattributes
- vivado/proc.tcl
- [adidng non-'v' prefix support to SubmoduleCheck()](https://github.com/slaclab/ruckus/commit/f3f3f043848a51399e2c78c74b907deff761201b)
- [Update .gitattributes](https://github.com/slaclab/ruckus/commit/c88bedcd3ae425a37e8106104493ea920de48965)
> Release Candidate v.4.1.6

- vivado/proc/debug_probes.tcl
- Allow the user to select the range in the netlist values
- If I don't set the range, I get all values in the wildcard list
- Result: `tData[511:0]` (512 values)
```tcl
ConfigProbe ${ilaName} {U_Hsio/U_CXP/U_Core/U_Rx/U_Mux/r[rxMaster][tData][*]}
```
- I can use the range to only add probes to bits 0 through 127
- Result: `tData[127:0]` (127values)
```tcl
ConfigProbe ${ilaName} {U_Hsio/U_CXP/U_Core/U_Rx/U_Mux/r[rxMaster][tData][*]} 0 127
```
> adding netname list range support to ConfigProbe()

- vivado/vcs.tcl
- [Vivado 2022.2 fixed more_options properties in export_simulation](https://github.com/slaclab/ruckus/commit/9b5848ff6f1d0cc5cd8e9e498def8c1f6258e23a)
- [initializing all config_compile_simlib's -cfgopt](https://github.com/slaclab/ruckus/commit/d2a68e4d9198f74f1a3165f16f82bb1fc790c152)
> Vivado Patch for VCS + 2022.2

- vivado/xsim.tcl
As exercised in [this commit first](https://github.com/slaclab/snl-trans-FES/commit/3b8c21cd7aad925749e817a86fb5f7f13e30ef34), and [also this one](b121ba3562eeb5780d7a54c0a936082cb244679d), the command `$ make xsim` produces a valid XSIM result.
The said commit from the repo linked avove points to the ruckus commit/branch that is to be merged with this request.
Rolling back the changes of the `xsim.tcl` script shows that there was an issue with re-defining the top-level of the simulation design.
> xsim.tcl: remove top-level re-definition that seems to break the xsim Makefile rule + xsim-dev merge

- system_vivado.mk
- vivado/msim.tcl
- vivado/qsim.tcl
- vivado/xsim.tcl
Hi Larry,
I've been using ruckus for projects I've been working on (its great! Thanks for developing it), and I added support for Vivado simulation using either ModelSim or Questa.
The msim.tcl script automatically detect whether you're using ModelSim or Questa (based on either what you have on your PATH or by explicitly using an environmental variable, MSIM_PATH), and whether you need to compile or not simulation libraries and then starts the simulation (its different compared to the VCS tcl script, since here no scripts are generated, but works more like the XSim tcl script).
The only thing Im not able to figure out is an error compiling the simulation libraries. If I run the `compile_simlib` in the  "ruckus environment" I get errors, but if I ran the identical command on a separate …
> Added ModelSim/Questa simulation support

- scripts/createNewRepo.py
- [Team.set_repo_permission() is deprecated, use Team.update_team_repository() instead](https://github.com/slaclab/ruckus/commit/64abc22765ce0e235194f4d993580a30ac4bd47f)
- [updating branch protection creation](https://github.com/slaclab/ruckus/commit/49c635c1222124a9f3d9962e6e0d1563282fab6f)
> Updates to createNewRepo.py

- scripts/firmwareRelease.py
This PR update the firmwareRelease.py scripts to match with the latest conda formats, and using setuptools instead of the deprecated distutils. Also pip is used to install the python packages in conda.
By default the min python version is set to 3.7. This PR also allows the rogue and python version dependencies to be overridden by adding them to the CondaDependencies list:
CondaDependencies:
- 'rogue>=v5.18'
- 'python>=3.9'
- surf
- rce_gen3_fw_lib
This PR also will build python only packages as norarch.
> Updating scripts/firmwareRelease.py for conda

- ghdl/proc.tcl
- system_vivado.mk
- vivado/proc/ip_management.tcl
- [changing GZIP_BUILD_IMAGE default (if not defined) to 0](https://github.com/slaclab/ruckus/commit/50ae6cd31f87d78f1b1b50055082c0e0922a1874)
- [chaning BuildIpCores() to use PARALLEL_SYNTH instead of all CPUs](https://github.com/slaclab/ruckus/commit/f736080af1871fbae60329dac0423f0aff1f808a)
- [allow simulation source code in GHDL source list](https://github.com/slaclab/ruckus/commit/fe0e113ca3a7fcede3a9e07cc7fe3b57bfe95636)
> Release Candidate v4.8.4

- system_vcs.mk
- system_vivado.mk
- vivado/vcs.tcl
- Fixed the issue with Vivado 2023.1 changing sim_vcs_mx.sh format
- Cleaned up the  sim_vcs_mx.sh.tcl parsing in vcs.tcl as well
- Tested on both Vivado 2022.2 and Vivado 2023.1
> vivado/vcs.tcl Update

- system_vivado.mk
- vivado/sources.tcl
- vivado/vcs.tcl
List of changes:
**vivado/vcs.tcl**
- If `VCS_LIB_PATH` variable exists, then that is PATH where the vivado compiled libraries for VCS are, otherwise use default PATH `${VIVADO_INSTALL}/vcs-${VersionNumber}`
- if `VIVADO_PROJECT_SIM` exists, then set that as simulation name, otherwise set as `[get_property top [get_filesets sim_1]]` 
(NB the variable `VIVADO_PROJECT_SIM` is used also in vivado/xsim.tcl and vivado/msim.tcl scrips)
**vivado/sources.tcl**
- if `VIVADO_PROJECT_SIM` is set, then set it as simulation top level (otherwise you would have conflict if you run directly `make vcs` after a `make clean`. This might make the change in `vivado/vcs.tcl` concerning the use of `VIVADO_PROJECT_SIM` variable useless, but since that is what is done in both xsim.tcl and msim.tcl, I would leave …
> Added variables for VCS script generation

- .gitignore
- vivado/messages.tcl
- vivado/proc/code_loading.tcl
- vivado/proc/project_management.tcl
- vivado/project.tcl
- [Update .gitignore for slprj dir](https://github.com/slaclab/ruckus/commit/01f9241a131229e4c101916ae767c6e01150c0e2)
- #304 
- [config_webtalk TCL command removed in 2023.2](https://github.com/slaclab/ruckus/commit/a24b37ed4552dcb0fcc64e584bc5495f3d19a442)
- [updating CheckVivadoVersion() for 2023.2 release](https://github.com/slaclab/ruckus/commit/2c4830881150412a87ffd897219e8c6440a7779a)
> Release Candidate v4.6.0

- vivado/xsim.tcl
The XSIM integration currently uses `wait_on_run` on a design run called `sim_1`. Since Vivado treats XSIM simulation runs as entirely separate to the design runs, `sim_1` isn't considered a run that you can call `wait_on_run` on (confirmed through `get_runs` returning only `synth_1` and `impl_1` despite being able to run a simulation run, and the `create_run` command only having options for synthesis and implementation flows).
The run command executed just prior to this line is already a blocking call, so the `wait_on_run` isn't necessary and this PR removes it.
I'm not sure if this has changed at some point in Vivado's history, but I have confirmed that at least in 2023.2 there is no design run called `sim_1`. I had a look at the recent release notes and didn't see anything relevant, …
> Prevent XSIM from attempting to block on non-existent run

- scripts/download_github_asset.py
- Useful script when trying to download a tag release asset from a `private repo`
> adding download_github_asset.py script

- scripts/firmwareRelease.py
- scripts/releaseNotes.py
This pull request enhances the release notes generation script by adding error handling for empty pull request (PR) descriptions. If an empty PR description is detected, the script will now delete the newly created tag both locally and on the remote (Github) repository
> firmwareRelease.py & releaseNotes.py

- .github/workflows/conda_build_win.yml
- .github/workflows/ruckus_ci.yml
- vivado/vcs.tcl
- https://github.com/slaclab/ruckus/pull/326
- [adding conda_build_win.yml](https://github.com/slaclab/ruckus/commit/e078784d9dee1d3bb2c8fb572ac07c713fa73101)
- [Reducing libzmq requirement >= 4.1.0 for RHEL8 and CENTOS7](https://github.com/slaclab/ruckus/pull/327/commits/225a710b3b932e5fb8dbb1154cee746a9c8d45a4)
- [bug fix to VCS setup_env.sh(.csh) generation to prevent picking up internal Vivado LD_LIBRARY_PATH](https://github.com/slaclab/ruckus/pull/327/commits/1282dcc6b677ce6f8fdae68e5508a006f4c7c08e)
> Release Candidate 4.15.0

- system_vitis_unified_hls.mk
- vitis/hls/build.py
- vitis/hls/create_proj.py
- Required due to deprecation on XSCT and vitis_hls 
- Tested using Vitis 2024.1
> Adding Vitis Unified HLS Python CLI

- vivado/proc/debug_probes.tcl
- [bug fix for Vivado 2024.1 and ILA generation via TCL scripting](https://github.com/slaclab/ruckus/commit/8992a5fb27dce286b7651b6d03a2d020f9ae8d7b)
> Release Candidate 4.16.2

- vivado/proc.tcl
- adding ability for custom user proc.tcl to be included with the 'submodule/ruckus/vivado/proc.tcl` loading
- Example of custom script: https://github.com/slaclab/Simple-10GbE-RUDP-KCU105-Example/blob/main/firmware/targets/Simple10GbeRudpKcu105Example/vivado/proc.tcl
> Update to vivado/proc.tcl

- .github/workflows/docker_build.yml
Fix typo in input reference.
Pending successfull Rogue deployment.
> hot fix: typo in input reference

- vivado/messages.tcl
- The previous behavior was allowing potential issue conditions that are bad design practice when the env var was not define
- This patch asserted an error message when these design practices are done and the env var associated is not defined
> logical bug fix for vivado/messages.tcl

- system_vitis_unified_hls.mk
- vitis/hls/build.py
When developing HLS IPs it is often useful to run the csim simulation several times. The infrastructure to run it is already there. This PR only exposes this functionality to the user.
> Added a CSIM target to HLS

- .github/workflows/conda_build_lib.yml
- .github/workflows/conda_build_proj.yml
- .github/workflows/conda_build_win.yml
- We're updating our instructions to use Miniforge instead of Miniconda, as it offers more flexible usage terms.
> Moved from Miniconda to Miniforge for useable Github CI conda package build scripts

- .github/workflows/conda_build_lib.yml
- .github/workflows/conda_build_proj.yml
- .github/workflows/conda_build_win.yml
- system_vivado.mk
- vivado/proc/output_files.tcl
- #351 
- [adding XSA export to CreateVersalOutputs() proc](https://github.com/slaclab/ruckus/pull/352/commits/3ff357780236bf18d43b6fa84ed0f7300bbbdf27)
- [removing symbol link due to recursivelinking in Vivado 2025.1 + boost](https://github.com/slaclab/ruckus/pull/352/commits/12aa971396bf0425df3f21e675c190de46d8189d)
- Here's the error message when the link was there and building the AMD VEK280 design when this pop up ... 
```
Starting Logic Optimization Task
Phase 1 Initialization
Phase 1.1 Core Generation And Design Setup
Phase 1.1.1 Generate And Synthesize MIG/Advanced IO Wizard Cores
Phase 1.1.1 Generate And Synthesize MIG/Advanced IO Wizard Cores | Checksum: 162497ba9
Time (s): cpu = 00:00:03 ; elapsed = 00:04:39 . Memory (MB): peak = 5687.711 ; gain = 3.023 ; free physical = 49113 …
```
> Release Candidate 4.18.0

- vivado/sources.tcl
- This is a useful feature to clean up the GUI view
- It also appears to make the Vivado GUI "snapper" when I tested on 2020.1
> updating vivado/sources.tcl for reorder_files + disable_unused

- scripts/createNewRepo.py
- Adding tid-id team to have read permission
- Adding tid-id-ecs team to have write permission
> Update createNewRepo.py's default writeTeam & readTeam
